spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://localhost:19092
          #          brokers: mr-ofd-bkafka01.ev.local:9092,mr-ofd-bkafka02.ev.local:9092
          auto-create-topics: false
        bindings:
          test:
            consumer:
              enable-dlq: true
      bindings:
        test:
          destination: test-1,test-2
          group: test
        test-error:
          destination: test-1-dlq,test-2-dlq
          group: test
