kafka:
  producer:
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: ru.max.kafka.serializer.JsonSerializer
    bootstrap.servers: localhost:19092,localhost:29092,localhost:39092