version: "3.7"

services:
  zookeeper:
    ports:
      - "2181:2181"
    image: confluentinc/cp-zookeeper:5.4.4
    environment:
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:5.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9094,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kafka-logs/
    volumes:
      - ./volumes/kafka:/tmp/kafka-logs

  kadeck-db:
    ports:
      - "5434:5432"
    image: postgres:12.6
    restart: on-failure:3
    volumes:
      - type: volume
        source: kadeck-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: "kadeckweb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  kadeck:
    ports:
      - "80:80"
    image: xeotek/kadeck-allinone:latest
    volumes:
      - /Users/alekseev_m/volumes/kadeck:/certificates
    environment:
      xeotek_kadeck_home: "kadeckweb"
      xeotek_kadeck_db_username: "postgres"
      xeotek_kadeck_db_password: "postgres"
      xeotek_kadeck_db_url: "jdbc:postgresql://kadeck-db:5432/kadeckweb"

volumes:
  kadeck-data:
  zookeeper-data:
  kafka-data: