version: "3.7"

services:
  zookeeper:
    network_mode: host
    image: confluentinc/cp-zookeeper:5.4.4
    environment:
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper

  kafka-1:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: /tmp/kafka-logs/
    volumes:
      - kafka-data-1

  kafka-2:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: /tmp/kafka-logs/
    volumes:
      - kafka-data-2

  kadeck-db:
    ports:
      - "5434:5432"
    image: postgres:12.6
    restart: on-failure:3
    volumes:
      - type: volume
        source: kadeck-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: "kadeckweb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  kadeck:
    ports:
      - "80:80"
    image: xeotek/kadeck-allinone:latest
    volumes:
      - /Users/alekseev_m/volumes/kadeck:/certificates
    environment:
      xeotek_kadeck_home: "kadeckweb"
      xeotek_kadeck_db_username: "postgres"
      xeotek_kadeck_db_password: "postgres"
      xeotek_kadeck_db_url: "jdbc:postgresql://kadeck-db:5432/kadeckweb"

volumes:
  kadeck-data:
  zookeeper-data:
  kafka-data-1:
  kafka-data-2: