server:
  port: 9090
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://localhost:19092
#          min-partition-count: 2
#          replication-factor: 1
#          auto-alter-topics: true